slogan: "Sharing makes me happy !"

menu:
  - title: "归档"
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: "分类"
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: "标签"
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: "关于我"
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/coderpan/hexo-theme-freemind.git
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/coderpan
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "My LinkedIn"
    url: https://www.linkedin.com/in/coderpan
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.ico
duoshuo_shortname: coderpan

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR
